import { ReactNode } from "react";
import type { Metadata } from "next";
import InstagramIcon from "@/components/svg/InstagramIcon";
import FacebookIcon from "@/components/svg/FacebookIcon";
import { getDictionary } from "@/language/getDictionary";
import Link from "next/link";
import "./globals.css";
import logo from "@/../public/static/Logo.webp";
import Image from "next/image";

type Dict = {
    nav: {
        home: string,
        about: string,
        room: string,
        tour: string,
        contact: string
    }
}

export const metadata: Metadata = {
	title: "La casa de mis recuerdos.",
	description: "Generated by show main page.",
};

export default async function RootLayout(
    {children, params}: Readonly<{children: ReactNode, params: { lang: string }}
    >
) {
    const dict : Dict = await getDictionary(params.lang, "header");

    return(
        <html lang={params.lang}>
            <body>
                <header>
                    <div className="footer-header-container">
                        <Image 
                            src={logo}
                            alt="Main logo"
                            width="210"
                        />
                        <nav>
                            <Link href="/">{dict.nav.home}</Link>
                            <Link href="/">{dict.nav.about}</Link>
                            <Link href="/rooms">{dict.nav.room}</Link>
                            <Link href="/tours">{dict.nav.tour}</Link>
                            <Link href="">{dict.nav.contact}</Link>
                        </nav>
                    </div>
                </header>
                <main>
                    <div className="container">
                        {children}
                    </div>
                </main>
                <footer>
                    <div className="footer-header-container">
                        <section>
                            <p>
                                Pino Suárez 508, Oaxaca Centro<br/>
                                C.P. 68000<br/>
                                Oaxaca, Oax. Mexico<br/>
                                Tel: <span>+52(951)5158483</span><br/>
                            </p>
                        </section>
                        <section>
                            <p>
                                lacasademisrecuerdos@gmail.com
                            </p>
                            <div className="footer-icons">
                                <FacebookIcon 
                                    href="https://www.facebook.com/lacasademisrecuerdos/?locale=es_LA"
                                />
                                <InstagramIcon 
                                    href="https://www.instagram.com/lacasademisrecuerdos/"
                                />
                            </div>
                        </section>
                    </div>
                </footer>
            </body>
        </html>
    );
}