import { Roboto, Roboto_Serif, Roboto_Mono, Scheherazade_New, Rasa } from "next/font/google"
import { Metadata } from "next";
import { ReactNode } from "react";
import { getDictionary } from "@/language/getDictionary";
import InstagramIcon from "@/components/svg/InstagramIcon";
import FacebookIcon from "@/components/svg/FacebookIcon";
import Header from "@/components/Header";
import "./globals.css";

type Dict = {
    nav: {
        home: string,
        about: string,
        room: string,
        tour: string,
        contact: string
    }
}

const roboto = Roboto ({
    subsets: ['latin'],
    variable: '--font-roboto',
    weight: '400',

})

const robotoSerif = Roboto_Serif ({
    subsets: ['latin'],
    variable: '--font-roboto-serif',
    weight: '400',

})

const robotoMono = Roboto_Mono ({
    subsets: ['latin'],
    variable: '--font-roboto-mono',
    weight: '400',

})

const scheherazadeNew = Scheherazade_New ({
    subsets: ['latin'],
    variable: '--font-scheherazade-new',
    weight: ['400', '700'],

})

const rasa = Rasa({
    subsets: ['latin'],
    variable: '--font-rasa',
    weight: ['400', '600', '700']
})

export const metadata: Metadata = {
	title: "La Casa de mis Recuerdos.",
	// description: "Generated by show main page.",
};

export default async function RootLayout(
    {children, params}: Readonly<{children: ReactNode, params: { lang: string }}
    >
) {
    const dict : Dict = await getDictionary(params.lang, "header");

    return(
        <>
            <html 
                lang={params.lang}
                className={`${roboto.variable} ${robotoMono.variable} ${robotoSerif.variable} ${scheherazadeNew.variable}`}
            >
                <body>
                    <Header 
                        nav={dict.nav}
                        lang={params.lang}
                    />
                    <main>
                        <div className="container">
                            {children}
                        </div>
                    </main>
                    <footer>
                        <div className="footer-header-container">
                            <section>
                                <p>
                                    Pino Suárez 508, Oaxaca Centro<br/>
                                    C.P. 68000<br/>
                                    Oaxaca, Oax. Mexico<br/>
                                    Tel: <span>+52(951)5158483</span><br/>
                                </p>
                            </section>
                            <section>
                                <p>
                                    lacasademisrecuerdos@gmail.com
                                </p>
                                <div className="footer-icons">
                                    <FacebookIcon 
                                        href="https://www.facebook.com/lacasademisrecuerdos/?locale=es_LA"
                                    />
                                    <InstagramIcon 
                                        href="https://www.instagram.com/lacasademisrecuerdos/"
                                    />
                                </div>
                            </section>
                        </div>
                    </footer>
                </body>
            </html>
        </>
    );
}