import Layout from "@/components/Layout";
import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Admin - Casa de mis recuerdos.",
	description: "Generated by edit main page.",
};

export default function ClientLayout(
    {children}: Readonly<{children: React.ReactNode}>
) {
    return(
        <html lang="en">
            <body>
                <Layout>
                    {children}
                </Layout>
            </body>
        </html>
    );
}