import RootProvider from "@/components/general/RootProvider";
import type { Metadata } from "next";
import { getServerSession, Session } from "next-auth";
import { authOptions } from "../lib/authOptions";
import { ColorProvider } from "@/contexts/ColorProvider";

export const metadata: Metadata = {
	title: "Admin - Casa de mis recuerdos.",
	description: "Generated by edit main page.",
};

export default async function ClientLayout(
    {children}: Readonly<{children: React.ReactNode}>
) {
    const session = await getServerSession(authOptions);

    return(
        <html lang="en">
            <body>
                <ColorProvider>
                    <RootProvider session={session}>
                        {children}
                    </RootProvider>
                </ColorProvider>
            </body>
        </html>
    );
}